### ISSUE TITLE
Create binary release

### ISSUE THREAD

**Issue by smistad** [SINTEFMedtek/FAST-Pathology#2]
Create a binary release for Windows and Ubuntu

**Comment by andreped** [comment]
Will have to wait until I have a more stable release, but will be done in the near future.

**Comment by andreped** [comment]
I just created binary releases for both Win10 and Ubuntu 18/20 and shared them. However, as I felt that the platform is still too unstable, I have only given it the version tag v0.1.0. Probably, in the near future, I can say that I am satisfied enough with the platform to give it the oh-so-holy v1.0.0, but that's for future André to enjoy.
