### ISSUE TITLE
Issue Running on Windows or Ubuntu

### ISSUE THREAD

**Issue by bnapora** [SINTEFMedtek/FAST-Pathology#5]
Hi,

I'm Interested in this project.  Attempted to run on both Windows and Ubuntu.  I manually copied some fonts for Qt and I believe core dependencies are met.  When running on Ubuntu, getting the following error:
![image](https://user-images.githubusercontent.com/33367141/106950988-0ce76500-66e4-11eb-8bf1-b654e8bfeb16.png)

The windows verbose log is:
![image](https://user-images.githubusercontent.com/33367141/106951799-12917a80-66e5-11eb-8da6-6935edd2b1f2.png)

With application crashing at this point.

Any insights on how to address. 

Brian

**Comment by andreped** [comment]
Hello! Nice to see that you are interested. I will be happy to help :)

This is a recent bug we have only recently observed (like one week or so). I think we concluded with that the OpenCL version that follows with CUDA is not compatible with the most recent version of OpenCL that FAST depends on. However, no real solution to this problem has been found yet. Which CUDA version are you using? And did you install OpenCL through CUDA?

On the Ubuntu machine, could you try installing OpenCL through this command instead:
`sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev`

Let me know if that doesn't work for you. I will try debugging this tomorrow to see if I find a fix.

But perhaps I and @smistad should look into this tomorrow to see if we can find a permanent solution.

André

**Comment by bnapora** [comment]
I did install OpenCL via CUDA.  CUDA is Version 11.2:
![image](https://user-images.githubusercontent.com/33367141/106953760-9b111a80-66e7-11eb-828c-3110bc99177b.png)

I will try the suggestion of installing OpenCL from GL Toolkit.  Do you think that would require uninstallation of OpenCL from CUDA?

**Comment by andreped** [comment]
Oh, I think I had the exact same issue recently. Could you attempt to run this command on Ubuntu and report what you get:
`clinfo`

It might be that you do not have OpenCL installed on your machine. Do you have a dedicated GPU (NVIDIA) or perhaps an integrated GPU (Intel)?

**Comment by andreped** [comment]
Oh, but to use the platform, you need to have **CUDA 10.0** installed. However, CUDA is not required, but OpenCL and OpenGL are.

**Comment by bnapora** [comment]
Looks like libglu1-mesa-dev is already installed (I did do that in my attempt to troubleshoot)
![image](https://user-images.githubusercontent.com/33367141/106954104-28ed0580-66e8-11eb-8f7a-d9bb4c6040c1.png)

However when I run "clinfo"  I get "Number of platforms                                                 0"

**Comment by smistad** [comment]
@andrep, you don't need to have CUDA 10 installed, fastPhatology should run as long as you have OpenCL.
CUDA 10 is only required for the current version of fastPathology if you want tensorflow GPU or TensoRT inference for the current version.

The clGetPlatformsIds error is because it can't find any OpenCL platforms installed

**Comment by bnapora** [comment]
Also this is a dedicated NVIDIA Tesla P40 GPU

**Comment by smistad** [comment]
You need to install the nvidia opencl package. Don't remember the exact name, but I think it is the one called nvidia-opencl-icd.
So, `sudo apt install nvidia-opencl-icd`
Then try running clinfo again

**Comment by bnapora** [comment]
Get the following when attempting to install nvidia-opencl-icd
![image](https://user-images.githubusercontent.com/33367141/106954846-3656bf80-66e9-11eb-9747-ddb683536488.png)

Based on the machines NVIDIA-SMI out put, I assumed Driver Version 460 might work.  So also tried this:
![image](https://user-images.githubusercontent.com/33367141/106954955-5f775000-66e9-11eb-9cc3-4ae9da29526a.png)

Any other ideas?

**Comment by smistad** [comment]
According to my ubuntu machine which has the NVIDIA 450 driver, OpenCL is installed with the llibnvidia-compute-450.
So in your case, try only writing `sudo apt install libnvidia-compute-460`
You might also need the package ocl-icd-libopencl1, if it wasn't installed with clinfo: `sudo apt install ocl-icd-libopencl1`

**Comment by bnapora** [comment]
Had `ocl-icd-libopencl1` installed.  I clued in to only try the libnvidia-compute-460 library.  Unfortunately when it tries to install get a dpkg error:
![image](https://user-images.githubusercontent.com/33367141/106956033-dfea8080-66ea-11eb-92c6-86f171f6c3a1.png)

If you have any insights cool.  If not I'll try a few more things to try and get OpenCL working.

Do you think its also OpenCL not found on the Windows instance as well?

**Comment by smistad** [comment]
Hm, I haven't seen that issue before, but a quick google search gave this: https://askubuntu.com/questions/1252188/cuda-install-issue-invalid-cross-device-link

Seems to be the same error... some sort of package conflict

The answer suggest at the webpage is then:
(warning though: these commands can fudge up your cuda install or package manager...)
```
sudo dpkg -i --force-overwrite /var/cache/apt/archives/libnvidia-compute-460_460.32.03-0ubuntu0.18.04.1_amd64.deb
sudo apt --fix-broken install
```

Yes, it might be the same issue on windows...

**Comment by bnapora** [comment]
Thx...I'll give it a try here shortly.

**Comment by bnapora** [comment]
Well even the nvidia-smi indicates Driver 460 is installed, I attempted with 440 version (since that is CUDA 10.2, which supposedly works best on 18.04).  After installing: `sudo apt install libnvidia-compute-440 ` I'm not able to see OpenCL 1.2 when running clinfo

**Comment by bnapora** [comment]
It does not appear that OpenCL is is issue on Windows 10 machine.  Driver is present at: `C:\WINDOWS\system32\OpenCL.dll`. When launching exe with --verbose flag, application error's out at:
`INFO [22412] Loaded configuration file: C:/Program Files/FastPathology/bin/fast_configuration.txt
INFO [22412] Test data path: C:/ProgramData/FAST/data/
INFO [22412] Kernel source path: C:/Program Files/FastPathology/bin//..//kernels/
INFO [22412] Kernel binary path: C:/ProgramData/FAST/kernel_binaries/
INFO [22412] Documentation path: C:/Program Files/FastPathology/bin//..//doc/
INFO [22412] Pipeline path: C:/ProgramData/FAST/pipelines/
INFO [22412] Qt plugins path: C:/Program Files/FastPathology/bin//..//plugins/
INFO [22412] Library path: C:/Program Files/FastPathology/bin//..//bin/
INFO [22412] Creating new QApp
INFO [22412] Creating new GL context for computation thread
Temporary path: C:/Users/BrianNapora/AppData/Local/Temp/fastpathology-CMrwSq
INFO [22412] QApp already exists..
INFO [22412] Device manager initialize.. `

Does the application need elevated permissions on Windows?  I ran with Administrator privileges', but same result.  Is there any additional logging I can invoke to track down issue?

**Comment by smistad** [comment]
I am assuming this is the same machine with a NVIDIA GPU? Have you installed the cuda toolkit on windows?
I installed this version: cuda_11.0.2_451.48_win10.exe, and it works with fastpathology

**Comment by bnapora** [comment]
No this is a different machine, has NVIDIA GeForce GTX 1060.  I did not install CUDA Toolkit on Windows.  I understood from wiki that default installation of of `OpenCL.dll` was satisfactory.  Do you believe the entire CUDA Toolkit is necessary to install on Windows?

**Comment by smistad** [comment]
OpenCL.dll does not actually contain an opencl platform, it is just a loader. This allows multiple opencl platforms to be used on a system.

It might be that the nvidia graphics driver ships the opencl plattform (Intel and and does this on Windows i think..), but the cuda toolkit definitely includes it.

**Comment by bnapora** [comment]
Gotcha.  I will do some experiments on the Ubuntu instance I have running, then consider installing CUDA Toolkit on my laptop. 

Thanks for the help.

**Comment by andreped** [comment]
Glad you got it working! Just let us know if you have any future challenges :) For instance if you have a custom model you want to use in the platform. Some information can be found in the wiki.

As it seems like your problem has been solved, I will close this issue.
